/* ============================================================
   OFFGRD — generate-week Supabase Edge Function (Phase D)
   Turns the active week plan + play assignments + opponent scout
   data + week test results into a coach/player education package,
   generated by Claude ONCE per week per team and cached in
   week_plans.gen (offline-capable — it rides the normal plan sync).

   DEPLOY (either way):
   A) CLI:  supabase functions deploy generate-week --project-ref <ref>
            (this file goes to supabase/functions/generate-week/index.ts)
   B) Dashboard: Edge Functions → Deploy new function → name it
      exactly  generate-week  → paste this file.

   SECRETS (Dashboard → Edge Functions → Secrets, or CLI):
     supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
     supabase secrets set OFFGRD_MODEL=claude-sonnet-5     (optional)

   Security: caller must be signed in AND can_edit(team) — enforced
   via the caller's JWT + RLS (user-scoped client; no service_role).
   The ANON key here is public-safe; the Anthropic key never leaves
   the function.
   ============================================================ */
import { createClient } from "npm:@supabase/supabase-js@2";

const CORS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS, "Content-Type": "application/json" } });
}
function simpleHash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) { h = ((h << 5) - h + s.charCodeAt(i)) | 0; }
  return String(h);
}
function dist(rows: any[], key: string, top = 4): string {
  const c: Record<string, number> = {};
  rows.forEach((r) => { const v = r && r[key]; if (v && v !== "—") c[String(v)] = (c[String(v)] || 0) + 1; });
  const tot = Object.values(c).reduce((a, b) => a + b, 0);
  if (!tot) return "no data";
  return Object.entries(c).sort((a, b) => b[1] - a[1]).slice(0, top)
    .map(([k, n]) => `${k} ${Math.round((n / tot) * 100)}%`).join(", ");
}
function pct(n: number, d: number): string { return d ? Math.round((n / d) * 100) + "%" : "—"; }

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  try {
    const { team_id, force } = await req.json().catch(() => ({}));
    if (!team_id) return json({ error: "team_id required" }, 400);
    const auth = req.headers.get("Authorization") ?? "";
    const supa = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: auth } } },
    );
    const { data: userRes } = await supa.auth.getUser();
    if (!userRes?.user) return json({ error: "Not signed in" }, 401);
    const { data: canEdit } = await supa.rpc("can_edit", { t: team_id });
    if (!canEdit) return json({ error: "Only coaches can generate the briefing" }, 403);

    const { data: wp } = await supa.from("week_plans").select("*")
      .eq("team_id", team_id).eq("status", "active").maybeSingle();
    if (!wp) return json({ error: "No active week plan — start one on the Game Plan screen" }, 404);

    /* cache: same opponent + date + play list → return the stored briefing */
    const planPlayNames: string[] = [];
    (wp.buckets || []).forEach((b: any) => (b.plays || []).forEach((p: any) => {
      if (p && p.name && !planPlayNames.includes(p.name)) planPlayNames.push(p.name);
    }));
    if (!planPlayNames.length) return json({ error: "The week plan has no plays yet — commit calls to buckets first" }, 400);
    const inputsHash = simpleHash(JSON.stringify(["v3", wp.opponent, wp.game_date, planPlayNames.slice().sort()]));
    if (!force && wp.gen && wp.gen.inputs_hash === inputsHash) return json({ gen: wp.gen, cached: true });

    /* ---- gather context (all RLS-scoped to the caller's team) ---- */
    const [{ data: plays }, { data: games }, { data: roster }, { data: results }] = await Promise.all([
      supa.from("plays").select("id,name,family,formation,protection,qb_reads,ol_keys,data").eq("team_id", team_id),
      supa.from("scouting_games").select("opponent,side,rows").eq("team_id", team_id),
      supa.rpc("team_roster", { t: team_id }),
      supa.from("qb_results").select("user_id,quiz,score,total,created_at").eq("team_id", team_id)
        .order("created_at", { ascending: false }).limit(300),
    ]);

    /* opponent defensive tendencies — summarized, not dumped */
    const defRows: any[] = (games || []).filter((g: any) => g.side === "def" && g.opponent === wp.opponent)
      .flatMap((g: any) => g.rows || []);
    const offRows: any[] = (games || []).filter((g: any) => g.side === "off" && g.opponent === wp.opponent)
      .flatMap((g: any) => g.rows || []);
    const thirdLong = defRows.filter((r) => +r.down === 3 && +r.distance >= 7);
    const redZone = defRows.filter((r) => r.fieldZone === "REDZONE");
    const press = defRows.filter((r) => +r.pressure === 1);
    const tend = defRows.length
      ? [
        `Coverage overall: ${dist(defRows, "coverage")}`,
        `Front overall: ${dist(defRows, "front")}`,
        `Pressure rate: ${pct(press.length, defRows.length)}${press.length ? ` (looks: ${dist(press, "blitz", 3)})` : ""}`,
        thirdLong.length ? `3rd & long coverage: ${dist(thirdLong, "coverage", 3)} (${thirdLong.length} snaps)` : "",
        redZone.length ? `Red zone coverage: ${dist(redZone, "coverage", 3)} (${redZone.length} snaps)` : "",
        `Sample: ${defRows.length} defensive snaps`,
      ].filter(Boolean).join("\n")
      : "No tagged defensive data for this opponent — write the narrative from the plan itself and say the scout sample is thin.";
    /* their offense — what OUR DEFENSE faces */
    const runRows = offRows.filter((r) => /run/i.test(String(r.playType || "")));
    const sitO = (dn: number, lo: number, hi: number) =>
      offRows.filter((r) => +r.down === dn && +r.distance >= lo && +r.distance <= hi);
    const runPct = (rows: any[]) =>
      rows.length ? Math.round((rows.filter((r) => /run/i.test(String(r.playType || ""))).length / rows.length) * 100) + "% run (" + rows.length + " snaps)" : "no data";
    const offTend = offRows.length
      ? [
        `Overall: ${runPct(offRows)}; motion ${pct(offRows.filter((r) => +r.motion === 1).length, offRows.length)}`,
        `Top formations: ${dist(offRows, "formation", 4)}`,
        runRows.length ? `Run direction: ${dist(runRows, "direction", 3)}` : "",
        `1st & 10: ${runPct(sitO(1, 7, 99))} · 2nd & long: ${runPct(sitO(2, 7, 99))} · 3rd & short: ${runPct(sitO(3, 1, 3))} · 3rd & long: ${runPct(sitO(3, 7, 99))}`,
      ].filter(Boolean).join("\n")
      : "No tagged offensive data for this opponent — keep the defensive section brief and say the scout sample is thin.";
    const bucketNames = (wp.buckets || []).map((b: any) =>
      `${b.name} (${b.dn === "ANY" ? "any down" : b.dn + " down"} / ${b.db === "ANY" ? "any dist" : b.db}${b.zone && b.zone !== "ANY" ? " / " + b.zone : ""})`
    ).join("; ");

    /* plan plays with assignments + authored reads */
    const byName: Record<string, any> = {};
    (plays || []).forEach((p: any) => { if (p.name) byName[p.name.toLowerCase()] = p; });
    const planCtx = (wp.buckets || []).map((b: any) => {
      const ps = (b.plays || []).map((pl: any) => {
        const row = (pl.id && (plays || []).find((x: any) => x.id === pl.id)) || byName[String(pl.name || "").toLowerCase()];
        let extra = "";
        if (row) {
          const asns = ((row.data && row.data.players) || [])
            .map((q: any) => (q.asn || q.asnAuto) ? `${q.lab}: ${q.asn || q.asnAuto}` : "").filter(Boolean).slice(0, 12);
          if (asns.length) extra += ` | assignments: ${asns.join("; ")}`;
          if (row.data && row.data.qbNotes) extra += ` | QB notes: ${row.data.qbNotes}`;
          if (row.qb_reads) {
            const rd = Object.entries(row.qb_reads).map(([cv, v]: [string, any]) => `${cv}→${v && v.t}`).join(", ");
            if (rd) extra += ` | reads: ${rd}`;
          }
          if (row.formation) extra += ` | ${row.formation}`;
        }
        return `  - ${pl.name}${extra}`.slice(0, 500);
      }).join("\n");
      return `${b.name} (${b.dn === "ANY" ? "any down" : b.dn + " down"} / ${b.db === "ANY" ? "any dist" : b.db}${b.zone && b.zone !== "ANY" ? " / " + b.zone : ""}):\n${ps || "  (no calls committed)"}`;
    }).join("\n");

    /* O-line protection keys — the keyed fronts + who-blocks-whom (Phase 3) */
    const OLRULE: Record<string, string> = { bob: "big-on-big", climb: "climb to the backer", fan: "fan/out", combo: "combo then climb", pull: "pull", reach: "reach playside", down: "down block", kick: "kick out", scan: "scan/check", checkrel: "check-release", free: "free release" };
    const olSeen: Record<string, boolean> = {};
    const olCtx = (wp.buckets || []).flatMap((b: any) => (b.plays || [])).map((pl: any) => {
      if (!pl || !pl.name || olSeen[pl.name]) return ""; olSeen[pl.name] = true;
      const row = (pl.id && (plays || []).find((x: any) => x.id === pl.id)) || byName[String(pl.name || "").toLowerCase()];
      if (!row || !row.ol_keys || !row.ol_keys.keys || !Object.keys(row.ol_keys.keys).length) return "";
      const defs = (row.data && row.data.defs) || [];
      const kt = (k: any) => !k ? "" : (k.t === "def" ? ("blocks the " + ((defs[+k.di] || {}).lab || "man")) : (OLRULE[k.r] || k.r));
      const lines = Object.entries(row.ol_keys.keys).map(([lab, e]: [string, any]) => {
        let s = `${lab} ${kt(e.pre)}`;
        if (e.post) s += `, then after the stunt ${kt(e.post)}`;
        return s;
      });
      const stunts = (row.ol_keys.stunt && Object.keys(row.ol_keys.stunt).length) || defs.some((d: any) => d.route && d.route.length);
      return `${pl.name} vs ${row.ol_keys.front || "their front"}${stunts ? " (they stunt)" : ""}: ${lines.join("; ")}${row.ol_keys.note ? ` | alert: ${row.ol_keys.note}` : ""}`;
    }).filter(Boolean).join("\n");

    /* players + week test results */
    const players = (roster || []).filter((m: any) => m.role === "player");
    const pref = "Week vs " + (wp.opponent || "—");
    const wkRes: Record<string, { n: number; sum: number }> = {};
    (results || []).forEach((r: any) => {
      if (r.quiz && String(r.quiz).indexOf(pref) === 0) {
        const e = (wkRes[r.user_id] = wkRes[r.user_id] || { n: 0, sum: 0 });
        e.n++; e.sum += r.total ? r.score / r.total : 0;
      }
    });
    const rosterCtx = players.map((m: any) => {
      const e = wkRes[m.user_id];
      return `- user_id=${m.user_id} name=${m.full_name || m.email || "?"} pos=${m.position || "?"} weekTests=${e ? e.n : 0} avg=${e && e.n ? Math.round((e.sum / e.n) * 100) + "%" : "—"}`;
    }).join("\n");

    /* ---- Claude ---- */
    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) return json({ error: "ANTHROPIC_API_KEY is not set in Edge Function secrets" }, 500);
    const model = Deno.env.get("OFFGRD_MODEL") || "claude-sonnet-5";
    const prompt =
`You are OFFGRD's weekly education engine for a high-school football program. Write plainly, at a level a smart 16-year-old reads without effort, but never dumbed-down. Ground EVERYTHING in the data below — never invent tendencies that aren't shown.

OPPONENT: ${wp.opponent || "—"}   GAMEDAY: ${wp.game_date || "not set"}

OPPONENT DEFENSIVE TENDENCIES (what our OFFENSE attacks):
${tend}

OPPONENT OFFENSIVE TENDENCIES (what our DEFENSE must stop):
${offTend}

OUR SITUATION BUCKETS (use these exact names for defense.situations): ${bucketNames}

THIS WEEK'S OFFENSIVE PLAN (buckets → committed calls, with assignments/reads where drawn):
${planCtx}

THIS WEEK'S O-LINE PROTECTION KEYS (each blocker's job vs the opponent's front / stunt — the coach keyed these):
${olCtx || "(no protection keys drawn yet)"}

ROSTER PLAYERS AND THEIR WEEK-TEST PROGRESS SO FAR:
${rosterCtx || "(no players on the roster yet)"}

Return ONLY a valid JSON object — no markdown fences, no commentary — with exactly these keys:
{
 "narrative": "2-3 short paragraphs for Monday: how this opponent plays defense, what our plan attacks and why. Coaches and players both read this.",
 "keys": [
   { "text": "short key to the game", "positions": ["TEAM"] },
   { "text": "position-specific key", "positions": ["QB"] },
   { "text": "another key", "positions": ["OL"] }
 ],
 "plays": { "<play name exactly as listed>": { "why": "1-2 sentences: why this call vs THIS opponent's shown tendencies", "coaching": "one concrete coaching point" } },
 "ol": { "<play name exactly as listed in the protection keys>": { "front": "<the front they show>", "why": "1-2 sentences: why these blocking keys beat THIS opponent's front and its stunt", "coaching": "one concrete O-line coaching point (leverage, communication, or the alert)" } },
 "positions": { "QB": "...", "RB": "...", "WR": "...", "TE": "...", "OL": "..." },
 "remediation": { "<user_id>": "2 encouraging sentences: what to work on and which week test to take next" },
 "defense": {
   "narrative": "1-2 short paragraphs: how their offense attacks (grounded in their offensive tendencies) and how our defense answers",
   "keys": [
     { "text": "defensive key", "positions": ["TEAM"] },
     { "text": "DB-specific key", "positions": ["DB"] },
     { "text": "LB-specific key", "positions": ["LB"] }
   ],
   "situations": { "<bucket name exactly as listed>": "one sentence: the front/coverage/pressure answer for that situation and why" },
   "positions": { "DL": "...", "LB": "...", "DB": "..." }
 }
}
Rules: include every play listed in the plan in "plays". Include a play in "ol" ONLY if it appears in the O-LINE PROTECTION KEYS section, using its exact name; explain the "why" in terms of the keyed assignments and the front/stunt shown. positions = 2-3 sentences each about THIS week vs THIS opponent (omit a position if nothing useful to say). remediation ONLY for players with fewer than 2 week tests or an average below 80% — key strictly by their user_id; use their name inside the text. defense.situations must use the exact bucket names listed above; if there is no offensive data for the opponent, keep defense honest about the thin sample instead of inventing tendencies. Each key MUST be an object {text, positions[]} where positions is one or more of QB,RB,WR,TE,OL,DL,LB,DB,ST,TEAM — use TEAM only for genuinely whole-unit keys; never tag an O-line blocking assignment as TEAM or QB.`;

    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model, max_tokens: 8000, messages: [{ role: "user", content: prompt }] }),
    });
    if (!resp.ok) {
      const errTxt = await resp.text().catch(() => "");
      return json({ error: `Claude API ${resp.status}: ${errTxt.slice(0, 300)}` }, 502);
    }
    const out = await resp.json();
    /* join every text block (some models emit more than one), then cut to the outermost {...} */
    let text = (out.content || []).filter((b: any) => b && b.type === "text").map((b: any) => b.text || "").join("\n");
    text = text.replace(/```(?:json)?/gi, "").trim();
    const a = text.indexOf("{"), z = text.lastIndexOf("}");
    if (a >= 0 && z > a) text = text.slice(a, z + 1);
    let parsed: any;
    try { parsed = JSON.parse(text); }
    catch (_e) {
      console.error("generate-week parse failure", { stop_reason: out.stop_reason, preview: String(text).slice(0, 400) });
      const hint = out.stop_reason === "max_tokens" ? " (output hit the token limit — trim the plan or try again)" : "";
      return json({ error: "Claude returned unparseable output — try again" + hint }, 502);
    }

    const ALLOWED_KEY_POS = new Set(["QB","RB","WR","TE","OL","DL","LB","DB","ST","TEAM"]);
    function normalizeKeys(arr: any[]): Array<{ text: string; positions: string[] }> {
      if (!Array.isArray(arr)) return [];
      return arr.slice(0, 6).map((k) => {
        if (typeof k === "string") return { text: k, positions: ["TEAM"] };
        if (k && typeof k === "object") {
          const text = String(k.text || k.key || k.k || "").trim();
          let positions: any = k.positions || k.for || [];
          if (typeof positions === "string") positions = positions.split(/[,/|+\s]+/);
          if (!Array.isArray(positions)) positions = [];
          const cleaned = positions
            .map((p: any) => String(p || "").toUpperCase().trim())
            .filter((p: string) => ALLOWED_KEY_POS.has(p));
          return { text, positions: cleaned.length ? cleaned : ["TEAM"] };
        }
        return { text: String(k || ""), positions: ["TEAM"] };
      }).filter((x) => x.text);
    }

    const defParsed = parsed.defense && typeof parsed.defense === "object" ? parsed.defense : {};
    const gen = {
      v: 1,
      generated_at: new Date().toISOString(),
      model,
      inputs_hash: inputsHash,
      opponent: wp.opponent || "",
      narrative: String(parsed.narrative || ""),
      keys: normalizeKeys(parsed.keys),
      plays: parsed.plays && typeof parsed.plays === "object" ? parsed.plays : {},
      ol: parsed.ol && typeof parsed.ol === "object" ? parsed.ol : {},
      positions: parsed.positions && typeof parsed.positions === "object" ? parsed.positions : {},
      remediation: parsed.remediation && typeof parsed.remediation === "object" ? parsed.remediation : {},
      defense: {
        ...defParsed,
        keys: normalizeKeys(defParsed.keys),
      },
    };
    /* Deterministic opponent looks for week_autotest / def_aligns seeding */
    try {
      const covCounts: Record<string, number> = {};
      const frontCounts: Record<string, number> = {};
      defRows.forEach((r) => {
        const c = String(r?.coverage || "");
        if (c && c !== "—") covCounts[c] = (covCounts[c] || 0) + 1;
        const f = String(r?.front || "");
        if (f && f !== "—") frontCounts[f] = (frontCounts[f] || 0) + 1;
      });
      const looks = Object.entries(covCounts)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 6)
        .map(([coverage, n]) => ({
          coverage,
          n,
          pct: defRows.length ? Math.round((n / defRows.length) * 100) : 0,
        }));
      const topFront = Object.entries(frontCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "";
      gen.defense = gen.defense && typeof gen.defense === "object" ? gen.defense : {};
      gen.defense.looks = looks;
      gen.defense.top_front = topFront;
      const alignments: Record<string, Record<string, unknown>> = {};
      looks.forEach((L) => {
        const key = /tampa/i.test(L.coverage)
          ? "Tampa 2"
          : (/[0-4]/.test(L.coverage) ? `Cover ${L.coverage.match(/[0-4]/)?.[0]}` : L.coverage);
        alignments[key] = { _auto: true, _seed: true, _front: topFront, _pct: L.pct };
      });
      gen.defense.alignments = alignments;
    } catch (_e) { /* non-fatal */ }
    const { error: upErr } = await supa.from("week_plans").update({ gen }).eq("id", wp.id);
    if (upErr) return json({ error: "Generated but couldn't save: " + upErr.message }, 500);
    return json({ gen, cached: false });
  } catch (e) {
    return json({ error: String((e as any)?.message || e) }, 500);
  }
});
